# fly.toml app configuration file generated for fs-gemini-chat on 2025-09-25
# Docs: https://fly.io/docs/reference/configuration/
app = "fs-gemini-chat"
primary_region = "sin" # ganti sesuai kebutuhan (misal: sin, syd, sjc, fra)
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "npm run migrate:deploy"

[env]
  NODE_ENV = "production"
  NITRO_PORT = "3000"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  size = "shared-cpu-1x" # atau upgrade sesuai kebutuhan
  memory = "512mb"

[[services]]
  internal_port = 3000
  protocol = "tcp"
  processes = ["app"]

  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "30s"
    restart_limit = 0
