[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# Environment variables yang akan di-set di Netlify dashboard
# DATABASE_URL - PostgreSQL connection string
# GOOGLE_API_KEY - Google Gemini API key
# NUXT_LOGTO_APP_SECRET - Logto app secret
# NUXT_LOGTO_COOKIE_ENCRYPTION_KEY - Logto cookie encryption key
# NUXT_LOGTO_ENDPOINT - Logto endpoint URL
# NUXT_LOGTO_APP_ID - Logto app ID
# APP_NAME - Application name