[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = ".netlify/functions-internal"
  node_bundler = "esbuild"
  included_files = [
    "node_modules/@prisma/client/**",
    "node_modules/.prisma/client/**",
    "prisma/schema.prisma"
  ]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
